services:
  task-manager:
    build: .
    image: host.docker.internal:5001/task-manager:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - redis
    labels:
      - com.packtpub.compose.app=task-manager
    networks:
      - task-manager-public-network
      - redis-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    labels:
      - com.packtpub.compose.app=task-manager
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - redis-network
  redis-populate:
    image: redis
    entrypoint: ["/redis-populate.sh", "/redis-populate.txt"]
    depends_on:
      - redis
    env_file:
      - ./.env.redis-populate
    volumes:
      - ./redis-populate.txt:/redis-populate.txt
      - ./redis-populate.sh:/redis-populate.sh
    labels:
      - com.packtpub.compose.app=task-manager
    networks:
      - redis-network
  redis-backup:
    image: bash
    entrypoint: ["/snapshot-backup.sh"]
    depends_on:
      - redis
    environment:
      - BACKUP_PERIOD=10
    volumes:
      - ./snapshot-backup.sh:/snapshot-backup.sh
      - redis-data:/data:ro
      - backup:/backup
    labels:
      - com.packtpub.compose.app=task-manager
    networks:
      - redis-network
volumes:
  redis-data:
    labels:
      - com.packtpub.compose.app=task-manager
  backup:
    labels:
      - com.packtpub.compose.app=task-manager
networks:
  task-manager-public-network:
    labels:
      - com.packtpub.compose.app=task-manager
  redis-network:
    labels:
      - com.packtpub.compose.app=task-manager
